version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 20
    directory: /
    schedule:
      interval: daily
    commit-message:
      include: scope
      prefix: chore
    reviewers:
      - oadpoaw

  - package-ecosystem: npm
    open-pull-requests-limit: 20
    directory: sloshdb.js
    schedule:
      interval: daily
    commit-message:
      include: scope
      prefix: chore
    reviewers:
      - oadpoaw

  - package-ecosystem: npm
    open-pull-requests-limit: 20
    directory: xandra
    schedule:
      interval: daily
    commit-message:
      include: scope
      prefix: chore
    reviewers:
      - oadpoaw
