name: Continuous Integration

on:
  push:
    paths:
      - "**.ts"
      - "package-lock.json"
    branches: [development]
  pull_request:
    paths:
      - "**.ts"
      - "package-lock.json"
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: npm ci

      - name: Compilation
        run: npm run build