name: pr-test-sloshdb.js

on:
  pull_request:
    branches: [development]
    paths:
      - sloshdb.js/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - working-directory: ./sloshdb.js
        run: |
          npm ci
          npm run build
          npm run test