name: pr-test-xandra

on:
  pull_request:
    branches: [development]
    paths:
      - xandra/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - working-directory: ./xandra
        run: |
          npm ci
          npm run lint
          npm run build
          npm test